#!/bin/sh
set -e
package_name=gpaste-applet-hide
case "$1" in
  remove)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/org.gnome.GPaste.Applet.desktop"
    ;;
  purge)
    dpkg-divert --package "$package_name" --rename --remove "/usr/share/applications/org.gnome.GPaste.Applet.desktop"
;;
esac
exit 0
